// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOeSKnZvl22Oh45AgI51TkwsqzY3YKhY',
    appId: '1:664974297230:web:2756fcfd4714ddc34861df',
    messagingSenderId: '664974297230',
    projectId: 'fir-9203c',
    authDomain: 'fir-9203c.firebaseapp.com',
    storageBucket: 'fir-9203c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmFM6mteDmnW1lIT58dun__cL6rT9Eug',
    appId: '1:664974297230:android:7413ac85c41bd6a44861df',
    messagingSenderId: '664974297230',
    projectId: 'fir-9203c',
    storageBucket: 'fir-9203c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfk83niDRF0IzzbKh3XxU2lswllDK7-mg',
    appId: '1:664974297230:ios:c6c2a0117c31d64f4861df',
    messagingSenderId: '664974297230',
    projectId: 'fir-9203c',
    storageBucket: 'fir-9203c.appspot.com',
    androidClientId: '664974297230-jvg150ssnfpb0nrfrfhpndb6t1ea222c.apps.googleusercontent.com',
    iosClientId: '664974297230-f6ppvrh2ngo8p79dvtsqh5odh2o2moh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfk83niDRF0IzzbKh3XxU2lswllDK7-mg',
    appId: '1:664974297230:ios:ccdaf77cf266b1f04861df',
    messagingSenderId: '664974297230',
    projectId: 'fir-9203c',
    storageBucket: 'fir-9203c.appspot.com',
    androidClientId: '664974297230-jvg150ssnfpb0nrfrfhpndb6t1ea222c.apps.googleusercontent.com',
    iosClientId: '664974297230-jr801t4rgb9jnrtb7pugm18mmhq7f04m.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
